# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: login
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    # - run: ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u chucklangford --password-stdin
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/chucklangford/test-node/test-node-chuck:1.0.0 .
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/chucklangford/test-node/test-node-chuck:1.0.0
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
